[project]
name = "gr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pdfplumber>=0.11.7",
    "pypdf2>=3.0.1",
    "unstructured[pdf]>=0.18.15",
]
